services:
  standard-web:
    restart: unless-stopped

  standard-api:
    restart: unless-stopped
    ports: !override
      - "127.0.0.1:8000:8000"

  standard-db:
    restart: unless-stopped
    ports: !override
      - "127.0.0.1:5432:5432"
